Repository jonsondrem/repost-frontend, pull requests merged in 2020-04, with the labels that each got.

#23 Login
  package-lock.json
  package.json
  src/components/Login.vue
  src/components/Navbar.vue
  src/pages/Login/App.vue
  src/pages/Login/main.js
Labels: enhancement

#24 MPA to SPA conversion
  src/App.vue
  src/api/index.js
  src/components/DisplayPost.vue
  src/components/DisplayUser.vue
  src/components/HomePostsData.vue
  src/components/Login.vue
  src/components/Navbar.vue
  src/components/ResubPostsData.vue
  src/components/ResubsList.vue
  src/main.js
  src/pages/Home/App.vue
  src/pages/Home/main.js
  src/pages/Login/App.vue
  src/pages/Login/main.js
  src/pages/Resubs/App.vue
  src/pages/Resubs/main.js
  src/pages/Support/App.vue
  src/pages/Support/main.js
  src/pages/Users/App.vue
  src/pages/Users/main.js
  src/router/index.js
  vue.config.js
Labels: enhancement

#25 Fixed issue where logo was overriding resublist
  src/components/ResubsList.vue
Labels: bug

#27 404 page created and fixed styling
  package-lock.json
  package.json
  src/components/Navbar.vue
  src/components/PostList.vue
  src/router/index.js
  src/views/NotFound.vue
  src/views/Resub.vue
  src/views/User.vue
Labels: enhancement

#29 Add API dropdown menu and support stricter OAuth2 login
  src/api/index.js
  src/components/Navbar.vue
  src/main.js
  src/views/Home.vue
  src/views/Login.vue
  src/views/Post.vue
  src/views/Resub.vue
  src/views/Resubs.vue
  src/views/User.vue
Labels: bug, enhancement

#30 Create post
  src/router/index.js
  src/views/Post.vue
  src/views/PostForm.vue
  src/views/Resub.vue
Labels: enhancement

#32 Implement concurrent loading and progress bar
  package.json
  src/components/Navbar.vue
  src/components/PostList.vue
  src/main.js
  src/router/index.js
  src/views/Home.vue
  src/views/Login.vue
  src/views/NotFound.vue
  src/views/Post.vue
  src/views/PostForm.vue
  src/views/Resub.vue
  src/views/Resubs.vue
  src/views/User.vue
Labels: enhancement

#33 Redirect to previous path when logging in
  src/views/Login.vue
Labels: enhancement

#34 Add store for current user and model localStorage items
  src/components/Navbar.vue
  src/main.js
  src/store/index.js
  src/views/Login.vue
  src/views/Post.vue
  src/views/PostForm.vue
  src/views/Resub.vue
Labels: enhancement

#41 Make forms components and add resub form
  src/components/FormPage.vue
  src/components/Navbar.vue
  src/router/index.js
  src/views/Post.vue
  src/views/PostForm.vue
  src/views/Resub.vue
  src/views/ResubForm.vue
  src/views/Resubs.vue
Labels: enhancement

#44 Use form data for client_id with no secret
  .env
  src/api/index.js
  src/views/Login.vue
Labels: enhancement

#45 Handle when no posts are found in home page
  src/components/Notice.vue
  src/views/Home.vue
Labels: bug, enhancement

#37 Added comment-section functionality
  src/components/EditAndDelete.vue
  src/components/Reply.vue
  src/views/Post.vue
Labels: enhancement

#47 Fix post edit and delete
  src/components/EditAndDelete.vue
  src/views/Post.vue
Labels: bug

#46 Base selected API on index
  src/api/index.js
  src/components/Navbar.vue
  src/store/index.js
Labels: bug
